### ISSUE TITLE
Add support for Minix Neo X8-H

### ISSUE THREAD

**Issue by chris-tina** [woodenshark/prismatik-for-android#44]
Multiple requests saying that screen grabbing mode doesn't work in Minix Neo X8-H, Android 4.4.2

**Comment by chris-tina** [comment]
https://gist.github.com/chris-tina/1659f06162067843fab7

**Comment by chris-tina** [comment]
12-07 21:46:06.363 10997 11464 E AndroidRuntime: FATAL EXCEPTION: Timer-7

12-07 21:46:06.363 10997 11464 E AndroidRuntime: Process: com.prismadroid.unity, PID: 10997

12-07 21:46:06.363 10997 11464 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [Timer-7]

12-07 21:46:06.363 10997 11464 E AndroidRuntime: Unity version     : 4.5.2f1

12-07 21:46:06.363 10997 11464 E AndroidRuntime: Device model      : MINIX NEO-X8-H

12-07 21:46:06.363 10997 11464 E AndroidRuntime: Device fingerprint: MBX/k200/k200:4.4.2/KOT49H/20140722:user/test-keys

12-07 21:46:06.363 10997 11464 E AndroidRuntime: 

12-07 21:46:06.363 10997 11464 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException

12-07 21:46:06.363 10997 11464 E AndroidRuntime:    at android.os.BinderProxy.transact(Native Method)

12-07 21:46:06.363 10997 11464 E AndroidRuntime:    at com.woodenshark.prismatik.ScrCapService$Stub$Proxy.captureZones(ScrCapService.java:95)

12-07 21:46:06.363 10997 11464 E AndroidRuntime:    at com.woodenshark.prismatik.server.ScreenshotServerManager.captureZones(ScreenshotServerManager.java:109)

12-07 21:46:06.363 10997 11464 E AndroidRuntime:    at com.woodenshark.prismatik.mode.ModeController_AverageColor.takeColors(ModeController_AverageColor.java:178)

12-07 21:46:06.363 10997 11464 E AndroidRuntime:    at com.woodenshark.prismatik.mode.ModeController_AverageColor$2.run(ModeController_AverageColor.java:142)

12-07 21:46:06.363 10997 11464 E AndroidRuntime:    at java.util.Timer$TimerImpl.run(Timer.java:284)

12-07 21:46:06.363   475   932 W ActivityManager:   Force finishing activity com.prismadroid.unity/com.woodenshark.prismatik.unity.VideoTestActivity

12-07 21:46:06.363   475   932 W ActivityManager:   Force finishing activity com.prismadroid.unity/com.woodenshark.prismatik.unity.MainActivity

**Comment by chris-tina** [comment]
duplicate of #40
