### ISSUE TITLE
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.ClassCastException: android.widget.RemoteViews$SetOnClickPendingIntent cannot be cast to android.widget.RemoteViews$ReflectionAction

### ISSUE THREAD

**Issue by e-yes** [woodenshark/prismatik-for-android#45]
``` bash
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.ClassCastException: android.widget.RemoteViews$SetOnClickPendingIntent cannot be cast to android.widget.RemoteViews$ReflectionAction
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:592)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by LanderlYoung** [comment]
This seems to be an samsung related bug. Only happes on samsung device running 4.0.4.
