### ISSUE TITLE
android.os.DeadObjectException

### ISSUE THREAD

**Issue by e-yes** [woodenshark/prismatik-for-android#51]
``` bash
java.lang.RuntimeException: Package manager has died
at android.app.ApplicationPackageManager.checkPermission(ApplicationPackageManager.java:305)
at com.bugsense.trace.Utils.CheckNetworkConnection(Unknown Source)
at com.bugsense.trace.Utils.isWifiOn(Unknown Source)
at com.bugsense.trace.Utils.setProperties(Unknown Source)
at com.bugsense.trace.BugSenseHandler.startSession(Unknown Source)
at com.bugsense.trace.BugSenseHandler$1.run(Unknown Source)
at java.lang.Thread.run(Thread.java:856)
Caused by: android.os.DeadObjectException
at android.os.BinderProxy.transact(Native Method)
at android.content.pm.IPackageManager$Stub$Proxy.checkPermission(IPackageManager.java:1714)
at android.app.ApplicationPackageManager.checkPermission(ApplicationPackageManager.java:303)
... 6 more

```

**Comment by ichbinwaber** [comment]
Users use anti-virus software for hardware acceleration causes some background services to be killed, resulting in the exception
